// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nutra.Data;

#nullable disable

namespace nutra.api.Migrations
{
    [DbContext(typeof(AlimentosContext))]
    [Migration("20260319175934_LocalUserProjection")]
    partial class LocalUserProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nutra.Models.Alimentos.Fabricantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Acucar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<string>("Dose")
                        .HasColumnType("text");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraMonoinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraPoliinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraSaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraTrans")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Porcao")
                        .HasColumnType("double precision");

                    b.Property<string>("PorcaoTexto")
                        .HasColumnType("text");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.Property<string>("Unidade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.FastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Acucar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<string>("Dose")
                        .HasColumnType("text");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraMonoinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraPoliinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraSaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraTrans")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Porcao")
                        .HasColumnType("double precision");

                    b.Property<string>("PorcaoTexto")
                        .HasColumnType("text");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.Property<string>("Unidade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FastFoods");
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.Genericos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Acucar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<string>("CategoriaPrincipal")
                        .HasColumnType("text");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<string>("Dose")
                        .HasColumnType("text");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraMonoinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraPoliinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraSaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraTrans")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Porcao")
                        .HasColumnType("double precision");

                    b.Property<string>("PorcaoTexto")
                        .HasColumnType("text");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.Property<string>("SubCategoria")
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genericos");
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.Tbca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AcidosGraxosMonoinsaturadosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcidosGraxosPoliinsaturadosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcidosGraxosSaturadosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcidosGraxosTransG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcucarDeAdicaoG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AlcoolG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AlfaTocoferolVitaminaEMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CalcioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CarboidratoDisponivelG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CarboidratoTotalG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CinzasG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CobreMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ColesterolMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKJ")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EquivalenteDeFolatoMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("FerroMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("FibraAlimentarG")
                        .HasColumnType("double precision");

                    b.Property<double?>("FosforoMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Grupo")
                        .HasColumnType("text");

                    b.Property<double?>("LipidiosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagnesioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManganesMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<double?>("NiacinaMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NomeCientifico")
                        .HasColumnType("text");

                    b.Property<double?>("PotassioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProteinaG")
                        .HasColumnType("double precision");

                    b.Property<double?>("RiboflavinaMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("SalDeAdicaoG")
                        .HasColumnType("double precision");

                    b.Property<double?>("SelenioMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("SodioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("TiaminaMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("UmidadeG")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaARaeMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaAReMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaB12Mcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaB6Mg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaCMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaDMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ZincoMg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Tbcas");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.AnamneseAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlimentosPreferidos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("AlimentosQueNaoGosta")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ComeComDistracao")
                        .HasColumnType("boolean");

                    b.Property<bool>("CompulsaoAlimentar")
                        .HasColumnType("boolean");

                    b.Property<double>("ConsumoAguaLitrosDia")
                        .HasColumnType("double precision");

                    b.Property<int>("ConsumoAlcool")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoCafeCha")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoDoces")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoFastFood")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoFrituras")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoFrutas")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoRefrigerantes")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumoVerduras")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPreenchimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoDietasAnteriores")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("FrequenciaEvacuacaoSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("HistoricoDietasRestritivas")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("HorarioAlmoco")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorarioCafeManha")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorarioCeia")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorarioJantar")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorarioLancheTarde")
                        .HasColumnType("interval");

                    b.Property<bool>("IntestinoRegular")
                        .HasColumnType("boolean");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<string>("QueixasDigestivas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RefeicoesPorDia")
                        .HasColumnType("integer");

                    b.Property<string>("RefeicoesPuladas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SuplementosEmUso")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("AnamnesesAlimentares");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.AvaliacaoAntropometrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("BioAguaCorporalLitros")
                        .HasColumnType("double precision");

                    b.Property<int?>("BioGorduraVisceralNivel")
                        .HasColumnType("integer");

                    b.Property<int?>("BioIdadeMetabolica")
                        .HasColumnType("integer");

                    b.Property<double?>("BioMassaGordaKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("BioMassaMagraKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("BioMassaOsseaKg")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("BioPercentualAgua")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BioPercentualGordura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double?>("BioTMBKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("CarboidratoRecomendadoG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaAbdomenCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaAntebracoDireitoCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaAntebracoEsquerdoCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaBracoDireitoCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaBracoEsquerdoCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaCinturaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaCoxaDireitaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaCoxaEsquerdaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaPanturrilhaDireitaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaPanturrilhaEsquerdaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaPescocoCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaQuadrilCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaToraxCm")
                        .HasColumnType("double precision");

                    b.Property<string>("ClassificacaoIMC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DensidadeCorporal")
                        .HasColumnType("decimal(6,4)");

                    b.Property<double?>("DobraAbdominalMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraAxilarMediaMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraBicepsMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraCoxaMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraPanturrilhaMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraPeitoralMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraSubescapularMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraSuprailiacaMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DobraTricepsMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("GET")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraRecomendadaG")
                        .HasColumnType("double precision");

                    b.Property<decimal>("IMC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double?>("MassaGordaEstimadaKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("MassaMagraEstimadaKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("PercentualGorduraDobrasCutaneas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PercentualGorduraEstimado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<double?>("PesoIdealDevineKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("PesoIdealIMCKg")
                        .HasColumnType("double precision");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("PossuiBioimpedancia")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfissionalResponsavelId")
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("ProteinaRecomendadaG")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProtocoloDobrasCutaneas")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RCQ")
                        .HasColumnType("decimal(4,2)");

                    b.Property<double?>("SomatorioDobras")
                        .HasColumnType("double precision");

                    b.Property<double?>("TMBHarrisBenedict")
                        .HasColumnType("double precision");

                    b.Property<double?>("TMBKatchMcArdle")
                        .HasColumnType("double precision");

                    b.Property<double?>("TMBMifflinStJeor")
                        .HasColumnType("double precision");

                    b.Property<double?>("TaxaMetabolicaAjustada")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.HasIndex("ProfissionalResponsavelId");

                    b.ToTable("AvaliacoesAntropometricas");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.FotoProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoAntropometricaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFoto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoAntropometricaId");

                    b.ToTable("FotosProgresso");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.FotoRefeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("RegistroAlimentarId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoRefeicao")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroAlimentarId");

                    b.HasIndex("UserId");

                    b.ToTable("FotosRefeicao");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.HistoricoClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AtivaAtualmente")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Condicao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDiagnostico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoOutra")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MedicamentosEmUso")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("HistoricoClinicos");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ItemModeloDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<double>("CarboidratoG")
                        .HasColumnType("double precision");

                    b.Property<double>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double>("FibraG")
                        .HasColumnType("double precision");

                    b.Property<double>("GorduraG")
                        .HasColumnType("double precision");

                    b.Property<string>("NomeAlimentoSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinaG")
                        .HasColumnType("double precision");

                    b.Property<double>("QuantidadeG")
                        .HasColumnType("double precision");

                    b.Property<int>("RefeicaoModeloDietaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTabela")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoModeloDietaId");

                    b.ToTable("ItensModelosDieta");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ItemRefeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<double>("CarboidratoG")
                        .HasColumnType("double precision");

                    b.Property<double>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double>("FibraG")
                        .HasColumnType("double precision");

                    b.Property<double>("GorduraG")
                        .HasColumnType("double precision");

                    b.Property<string>("NomeAlimentoSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinaG")
                        .HasColumnType("double precision");

                    b.Property<double>("QuantidadeG")
                        .HasColumnType("double precision");

                    b.Property<int>("RefeicaoPlanoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTabela")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoPlanoId");

                    b.ToTable("ItensRefeicao");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ModeloDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CaloriasBase")
                        .HasColumnType("double precision");

                    b.Property<double>("CarboidratoBaseG")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPorProfissionalId")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("GorduraBaseG")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroRefeicoesDia")
                        .HasColumnType("integer");

                    b.Property<int>("ObjetivoAlvo")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenciaAlimentarAlvo")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinaBaseG")
                        .HasColumnType("double precision");

                    b.Property<bool>("Publico")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorProfissionalId");

                    b.ToTable("ModelosDieta");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PlanoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AguaAlvoL")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CaloriasAlvoDiarias")
                        .HasColumnType("double precision");

                    b.Property<double>("CarboidratoAlvoG")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("FibraAlvoG")
                        .HasColumnType("double precision");

                    b.Property<double>("GorduraAlvoG")
                        .HasColumnType("double precision");

                    b.Property<int?>("ModeloDietaOrigemId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfissionalResponsavelId")
                        .HasColumnType("character varying(128)");

                    b.Property<double>("ProteinaAlvoG")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloDietaOrigemId");

                    b.HasIndex("PerfilNutricionalId");

                    b.HasIndex("ProfissionalResponsavelId");

                    b.ToTable("PlanosAlimentares");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PreferenciaAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<int>("Tabela")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("PreferenciaAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RefeicaoModeloDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("HorarioSugerido")
                        .HasColumnType("interval");

                    b.Property<int>("ModeloDietaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<double>("PercentualCaloricoSugerido")
                        .HasColumnType("double precision");

                    b.Property<int>("TipoRefeicao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloDietaId");

                    b.ToTable("RefeicoeModelosDieta");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RefeicaoPlano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("HorarioSugerido")
                        .HasColumnType("interval");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("PlanoAlimentarId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRefeicao")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCarboidratoG")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalEnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalFibraG")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalGorduraG")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalProteinaG")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlanoAlimentarId");

                    b.ToTable("RefeicoesPlanejadas");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RegistroAlimentar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AguaTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("AlimentoIdOrigem")
                        .HasColumnType("integer");

                    b.Property<double>("CarboTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosNutricionaisCompletosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataConsumo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EnergiaKcalTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("FibraTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("GorduraTotal")
                        .HasColumnType("double precision");

                    b.Property<int?>("ItemRefeicaoPlanoId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeAlimentoSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanoAlimentarId")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinaTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("QuantidadeConsumidaG")
                        .HasColumnType("double precision");

                    b.Property<int>("Refeicao")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTabela")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ItemRefeicaoPlanoId");

                    b.HasIndex("PlanoAlimentarId");

                    b.HasIndex("UserId");

                    b.ToTable("RegistroAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RestricaoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompostoOrganico")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("RestricaoAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.SubstituicaoEquivalente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<double>("CarboidratoG")
                        .HasColumnType("double precision");

                    b.Property<double>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double>("FibraG")
                        .HasColumnType("double precision");

                    b.Property<double>("GorduraG")
                        .HasColumnType("double precision");

                    b.Property<int>("ItemRefeicaoId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeAlimento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("ProteinaG")
                        .HasColumnType("double precision");

                    b.Property<double>("QuantidadeG")
                        .HasColumnType("double precision");

                    b.Property<int>("TipoTabela")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRefeicaoId");

                    b.ToTable("SubstituicoesEquivalentes");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.Assinatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewaySubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PerfilProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int>("Plano")
                        .HasColumnType("integer");

                    b.Property<bool>("RenovacaoAutomatica")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilProfissionalId")
                        .IsUnique();

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PerfilProfissionalId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilProfissionalId");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.MetaNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AguaDiaria")
                        .HasColumnType("double precision");

                    b.Property<double>("CaloriasDiarias")
                        .HasColumnType("double precision");

                    b.Property<double>("CarboidratosDiarios")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DataCalculo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FibraDiaria")
                        .HasColumnType("double precision");

                    b.Property<double>("GordurasDiarias")
                        .HasColumnType("double precision");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinasDiarias")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("MetasNutricionais");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Equipamento")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("PerfisEquipamentos");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CircunferenciaBracoCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaCinturaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaQuadrilCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCondicoesMedicas")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("FatorAtividade")
                        .HasColumnType("double precision");

                    b.Property<bool>("Fumante")
                        .HasColumnType("boolean");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<int>("HabilidadeCulinaria")
                        .HasColumnType("integer");

                    b.Property<double?>("HorasSonoPorNoite")
                        .HasColumnType("double precision");

                    b.Property<int?>("MetaNutricionalAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("NivelAtividade")
                        .HasColumnType("integer");

                    b.Property<int>("Objetivo")
                        .HasColumnType("integer");

                    b.Property<string>("OcupacaoProfissional")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrcamentoMensal")
                        .HasColumnType("integer");

                    b.Property<double?>("PercentualGorduraCorporal")
                        .HasColumnType("double precision");

                    b.Property<double>("PesoAtualKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("PesoDesejadoKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("PossuiDoencasPreExistentes")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferenciaDieta")
                        .HasColumnType("integer");

                    b.Property<int?>("QualidadeSono")
                        .HasColumnType("integer");

                    b.Property<int>("RefeicoesPorDiaDesejadas")
                        .HasColumnType("integer");

                    b.Property<int>("TempoDisponivelPreparoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("MetaNutricionalAtualId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilProfissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnosExperiencia")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BioProfissional")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CRN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CRNRegiao")
                        .HasColumnType("integer");

                    b.Property<bool>("CRNVerificado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVerificacaoCRN")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaxPacientes")
                        .HasColumnType("integer");

                    b.Property<bool>("MultiClinicaHabilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlDiploma")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CRN")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PerfisProfissionais");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.RegistroBiometrico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CircunferenciaCinturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PercentualGordura")
                        .HasColumnType("double precision");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("RegistroBiometrico");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.VinculoPacienteProfissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAceite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataConvite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PacienteUserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PerfilProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("PerfilProfissionalId");

                    b.HasIndex("PacienteUserId", "PerfilProfissionalId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.ToTable("VinculosPacienteProfissional");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.AnamneseAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany("Anamneses")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.AvaliacaoAntropometrica", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany("AvaliacoesAntropometricas")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "ProfissionalResponsavel")
                        .WithMany()
                        .HasForeignKey("ProfissionalResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerfilNutricional");

                    b.Navigation("ProfissionalResponsavel");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.FotoProgresso", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.AvaliacaoAntropometrica", "AvaliacaoAntropometrica")
                        .WithMany("FotosProgresso")
                        .HasForeignKey("AvaliacaoAntropometricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoAntropometrica");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.FotoRefeicao", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.RegistroAlimentar", "RegistroAlimentar")
                        .WithMany("FotosRefeicao")
                        .HasForeignKey("RegistroAlimentarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroAlimentar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.HistoricoClinico", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany("HistoricosClinico")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ItemModeloDieta", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.RefeicaoModeloDieta", "RefeicaoModeloDieta")
                        .WithMany("Itens")
                        .HasForeignKey("RefeicaoModeloDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefeicaoModeloDieta");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ItemRefeicao", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.RefeicaoPlano", "RefeicaoPlano")
                        .WithMany("Itens")
                        .HasForeignKey("RefeicaoPlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefeicaoPlano");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ModeloDieta", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "CriadoPorProfissional")
                        .WithMany()
                        .HasForeignKey("CriadoPorProfissionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPorProfissional");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PlanoAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.ModeloDieta", "ModeloDietaOrigem")
                        .WithMany()
                        .HasForeignKey("ModeloDietaOrigemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany("PlanosAlimentares")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "ProfissionalResponsavel")
                        .WithMany()
                        .HasForeignKey("ProfissionalResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModeloDietaOrigem");

                    b.Navigation("PerfilNutricional");

                    b.Navigation("ProfissionalResponsavel");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PreferenciaAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "Perfil")
                        .WithMany("PreferenciasAlimentares")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RefeicaoModeloDieta", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.ModeloDieta", "ModeloDieta")
                        .WithMany("Refeicoes")
                        .HasForeignKey("ModeloDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloDieta");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RefeicaoPlano", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.PlanoAlimentar", "PlanoAlimentar")
                        .WithMany("RefeicoesPlanejadas")
                        .HasForeignKey("PlanoAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RegistroAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.ItemRefeicao", "ItemRefeicaoPlano")
                        .WithMany()
                        .HasForeignKey("ItemRefeicaoPlanoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nutra.Models.RegraNutricional.PlanoAlimentar", "PlanoAlimentar")
                        .WithMany()
                        .HasForeignKey("PlanoAlimentarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemRefeicaoPlano");

                    b.Navigation("PlanoAlimentar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RestricaoAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "Perfil")
                        .WithMany("RestricoesAlimentares")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.SubstituicaoEquivalente", b =>
                {
                    b.HasOne("Nutra.Models.RegraNutricional.ItemRefeicao", "ItemRefeicao")
                        .WithMany("SubstituicoesEquivalentes")
                        .HasForeignKey("ItemRefeicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemRefeicao");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.Assinatura", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilProfissional", "PerfilProfissional")
                        .WithOne("AssinaturaAtiva")
                        .HasForeignKey("Nutra.Models.Usuario.Assinatura", "PerfilProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilProfissional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.Clinica", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilProfissional", "PerfilProfissional")
                        .WithMany("Clinicas")
                        .HasForeignKey("PerfilProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilProfissional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.MetaNutricional", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany()
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilEquipamento", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany("EquipamentoDisponivel")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilNutricional", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.MetaNutricional", "MetaNutricional")
                        .WithMany()
                        .HasForeignKey("MetaNutricionalAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "User")
                        .WithOne("PerfilAtivo")
                        .HasForeignKey("Nutra.Models.Usuario.PerfilNutricional", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaNutricional");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilProfissional", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "User")
                        .WithOne("PerfilProfissional")
                        .HasForeignKey("Nutra.Models.Usuario.PerfilProfissional", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.RegistroBiometrico", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "Perfil")
                        .WithMany("HistoricoMedidas")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.VinculoPacienteProfissional", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId");

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "Paciente")
                        .WithMany("VinculosComoPaciente")
                        .HasForeignKey("PacienteUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nutra.Models.Usuario.PerfilProfissional", "Profissional")
                        .WithMany("Pacientes")
                        .HasForeignKey("PerfilProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.AvaliacaoAntropometrica", b =>
                {
                    b.Navigation("FotosProgresso");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ItemRefeicao", b =>
                {
                    b.Navigation("SubstituicoesEquivalentes");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.ModeloDieta", b =>
                {
                    b.Navigation("Refeicoes");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PlanoAlimentar", b =>
                {
                    b.Navigation("RefeicoesPlanejadas");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RefeicaoModeloDieta", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RefeicaoPlano", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RegistroAlimentar", b =>
                {
                    b.Navigation("FotosRefeicao");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.ApplicationUser", b =>
                {
                    b.Navigation("PerfilAtivo");

                    b.Navigation("PerfilProfissional");

                    b.Navigation("VinculosComoPaciente");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilNutricional", b =>
                {
                    b.Navigation("Anamneses");

                    b.Navigation("AvaliacoesAntropometricas");

                    b.Navigation("EquipamentoDisponivel");

                    b.Navigation("HistoricoMedidas");

                    b.Navigation("HistoricosClinico");

                    b.Navigation("PlanosAlimentares");

                    b.Navigation("PreferenciasAlimentares");

                    b.Navigation("RestricoesAlimentares");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilProfissional", b =>
                {
                    b.Navigation("AssinaturaAtiva");

                    b.Navigation("Clinicas");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
