// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nutra.Data;

#nullable disable

namespace Nutra.Migrations
{
    [DbContext(typeof(AlimentosContext))]
    [Migration("20260223010849_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.Fabricantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Acucar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraMonoinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraPoliinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraSaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraTrans")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Porcao")
                        .HasColumnType("double precision");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.FastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Acucar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraMonoinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraPoliinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraSaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraTrans")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Porcao")
                        .HasColumnType("double precision");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FastFoods");
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.Genericos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Acucar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<string>("CategoriaPrincipal")
                        .HasColumnType("text");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraMonoinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraPoliinsaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraSaturada")
                        .HasColumnType("double precision");

                    b.Property<double?>("GorduraTrans")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Porcao")
                        .HasColumnType("double precision");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.Property<string>("SubCategoria")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genericos");
                });

            modelBuilder.Entity("Nutra.Models.Alimentos.Tbca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AcidosGraxosMonoinsaturadosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcidosGraxosPoliinsaturadosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcidosGraxosSaturadosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcidosGraxosTransG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AcucarDeAdicaoG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AlcoolG")
                        .HasColumnType("double precision");

                    b.Property<double?>("AlfaTocoferolVitaminaEMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CalcioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CarboidratoDisponivelG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CarboidratoTotalG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CinzasG")
                        .HasColumnType("double precision");

                    b.Property<double?>("CobreMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ColesterolMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKJ")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EquivalenteDeFolatoMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("FerroMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("FibraAlimentarG")
                        .HasColumnType("double precision");

                    b.Property<double?>("FosforoMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Grupo")
                        .HasColumnType("text");

                    b.Property<double?>("LipidiosG")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagnesioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManganesMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<double?>("NiacinaMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NomeCientifico")
                        .HasColumnType("text");

                    b.Property<double?>("PotassioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProteinaG")
                        .HasColumnType("double precision");

                    b.Property<double?>("RiboflavinaMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("SalDeAdicaoG")
                        .HasColumnType("double precision");

                    b.Property<double?>("SelenioMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("SodioMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("TiaminaMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("UmidadeG")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaARaeMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaAReMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaB12Mcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaB6Mg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaCMg")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaDMcg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ZincoMg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Tbcas");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PreferenciaAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<int>("Tabela")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("PreferenciaAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RegistroAlimentar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AguaTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("AlimentoIdOrigem")
                        .HasColumnType("integer");

                    b.Property<double>("CarboTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("DadosNutricionaisCompletosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataConsumo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EnergiaKcalTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("FibraTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("GorduraTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("NomeAlimentoSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProteinaTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("QuantidadeConsumidaG")
                        .HasColumnType("double precision");

                    b.Property<int>("Refeicao")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTabela")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistroAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RestricaoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompostoOrganico")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("RestricaoAlimentar");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Nutra.Models.Usuario.MetaNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AguaDiaria")
                        .HasColumnType("double precision");

                    b.Property<double>("CaloriasDiarias")
                        .HasColumnType("double precision");

                    b.Property<double>("CarboidratosDiarios")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DataCalculo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FibraDiaria")
                        .HasColumnType("double precision");

                    b.Property<double>("GordurasDiarias")
                        .HasColumnType("double precision");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinasDiarias")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MetasNutricionais");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Equipamento")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("PerfisEquipamentos");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("CircunferenciaCinturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCondicoesMedicas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FatorAtividade")
                        .HasColumnType("double precision");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<int?>("MetaNutricionalAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("NivelAtividade")
                        .HasColumnType("integer");

                    b.Property<int>("Objetivo")
                        .HasColumnType("integer");

                    b.Property<string>("OcupacaoProfissional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PercentualGorduraCorporal")
                        .HasColumnType("double precision");

                    b.Property<double>("PesoAtualKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("PesoDesejadoKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("PossuiDoencasPreExistentes")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferenciaDieta")
                        .HasColumnType("integer");

                    b.Property<int>("RefeicoesPorDiaDesejadas")
                        .HasColumnType("integer");

                    b.Property<int>("TempoDisponivelPreparoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MetaNutricionalAtualId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.RegistroBiometrico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CircunferenciaCinturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PercentualGordura")
                        .HasColumnType("double precision");

                    b.Property<int>("PerfilNutricionalId")
                        .HasColumnType("integer");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PerfilNutricionalId");

                    b.ToTable("RegistroBiometrico");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.PreferenciaAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "Perfil")
                        .WithMany("PreferenciasAlimentares")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RegistroAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutra.Models.RegraNutricional.RestricaoAlimentar", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "Perfil")
                        .WithMany("RestricoesAlimentares")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilEquipamento", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "PerfilNutricional")
                        .WithMany("EquipamentoDisponivel")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilNutricional");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilNutricional", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.MetaNutricional", "MetaNutricional")
                        .WithOne("PerfilNutricional")
                        .HasForeignKey("Nutra.Models.Usuario.PerfilNutricional", "MetaNutricionalAtualId");

                    b.HasOne("Nutra.Models.Usuario.ApplicationUser", "User")
                        .WithOne("PerfilAtivo")
                        .HasForeignKey("Nutra.Models.Usuario.PerfilNutricional", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaNutricional");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.RegistroBiometrico", b =>
                {
                    b.HasOne("Nutra.Models.Usuario.PerfilNutricional", "Perfil")
                        .WithMany("HistoricoMedidas")
                        .HasForeignKey("PerfilNutricionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.ApplicationUser", b =>
                {
                    b.Navigation("PerfilAtivo");
                });

            modelBuilder.Entity("Nutra.Models.Usuario.MetaNutricional", b =>
                {
                    b.Navigation("PerfilNutricional")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutra.Models.Usuario.PerfilNutricional", b =>
                {
                    b.Navigation("EquipamentoDisponivel");

                    b.Navigation("HistoricoMedidas");

                    b.Navigation("PreferenciasAlimentares");

                    b.Navigation("RestricoesAlimentares");
                });
#pragma warning restore 612, 618
        }
    }
}
